// <auto-generated />
using System;
using Alakai.FestivalManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alakai.FestivalManager.Infrastructure.Migrations
{
    [DbContext(typeof(FestivalManagerDbContext))]
    [Migration("20260610185353_SimplifyPassTypeModel")]
    partial class SimplifyPassTypeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RegistrationCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId", "Year")
                        .IsUnique();

                    b.ToTable("Editions", (string)null);
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Festivals", (string)null);
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("EarlyBirdPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("FollowerCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("GroupPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("IndividualCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LeaderCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("MaxFollowerDifference")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLeaderDifference")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PassTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RegularPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PassTypeId", "Name")
                        .IsUnique();

                    b.ToTable("Levels", (string)null);
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.PassType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EditionId", "Name")
                        .IsUnique();

                    b.ToTable("PassTypes", (string)null);
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Edition", b =>
                {
                    b.HasOne("Alakai.FestivalManager.Domain.Entities.Festival", "Festival")
                        .WithMany("Editions")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Level", b =>
                {
                    b.HasOne("Alakai.FestivalManager.Domain.Entities.PassType", "PassType")
                        .WithMany("Levels")
                        .HasForeignKey("PassTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PassType");
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.PassType", b =>
                {
                    b.HasOne("Alakai.FestivalManager.Domain.Entities.Edition", "Edition")
                        .WithMany("PassTypes")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Edition", b =>
                {
                    b.Navigation("PassTypes");
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.Festival", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Alakai.FestivalManager.Domain.Entities.PassType", b =>
                {
                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
