# Rewrite all 4 JSON files with ALL keys needed by Register.razor and UserPanel.razor
# Run from repo root: .\fix_all_json_keys.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$i18n = "Alakai.FestivalManager.Admin\wwwroot\i18n"

[System.IO.File]::WriteAllText("$i18n\en.json", @'
{
  "loading": "Loading...",
  "Loading": "Loading...",
  "registration_unavailable": "Registration unavailable",
  "payment_success": "Payment completed!",
  "payment_failed": "Payment failed",
  "registration_confirmed": "Your registration is confirmed. Check your email for details.",
  "registration_submitted": "Registration submitted!",
  "go_to_login": "Go to login",
  "personal_details": "Personal Details",
  "name": "Name",
  "last_names": "Last Names",
  "email": "Email",
  "password": "Password",
  "phone_number": "Phone Number",
  "country": "Country",
  "city": "City",
  "select_pass": "Select your pass",
  "choose_parties": "Choose your party/ies",
  "select_level": "Select your level",
  "select_role": "Select your role",
  "register_with_partner": "Are you registering with a partner?",
  "yes": "Yes",
  "no": "No",
  "partner_email": "Partner's email",
  "group_code": "Group name / discount code",
  "select_payment": "Select payment type",
  "payment_split": "Split payment: pay 50% online now and the remaining 50% in 30 days",
  "total_now": "Total amount to pay online now",
  "total_deferred": "Total amount due within 10 days of receiving the confirmation email",
  "price": "Price:",
  "pay_now": "Pay now:",
  "accept_terms": "I accept the",
  "terms": "Terms & Conditions",
  "submit": "Register",
  "error_required_fields": "Please complete all required fields.",
  "error_accept_terms": "You must accept the Terms and Conditions to continue.",
  "error_select_pass": "Please select a pass to continue.",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "role_individual": "Individual",
  "up_registration": "Registration",
  "up_payment": "Payment",
  "up_competitions": "Competitions",
  "up_invoices": "Invoices",
  "up_accommodation": "Accommodation",
  "up_meals": "Meals",
  "up_buses": "Buses",
  "up_personal_details": "My personal details",
  "up_update_profile": "Update your personal details.",
  "up_first_name": "First Name",
  "up_last_name": "Last Name",
  "up_email": "Your email",
  "up_phone": "Phone",
  "up_country": "Country",
  "up_city": "City",
  "up_document": "Document Number",
  "up_postal_code": "Postal code",
  "up_birth_date": "Birth date",
  "up_save": "Save",
  "up_discard": "Discard",
  "up_edit": "Edit",
  "up_cancel": "Cancel",
  "up_my_registration": "My Registration details",
  "up_pass": "Pass",
  "up_level": "Level",
  "up_role": "Role",
  "up_partner": "Partner",
  "up_status": "Status",
  "up_amount": "Amount",
  "up_date": "Date",
  "up_pay_registration": "Pay your registration.",
  "up_registration_payment": "Registration Payment",
  "up_final_price": "Final Price",
  "up_discount_code": "Discount Code",
  "up_create_invoice": "Create Invoice",
  "up_invoice": "Invoice",
  "up_no_invoices": "There are no invoices available yet.",
  "up_actions": "Actions",
  "up_competition": "Competition",
  "up_no_competition": "You are not registered to any competition.",
  "up_delete_competition": "Delete competition",
  "up_no_spots": "No spots available",
  "up_select_competition": "Select competition",
  "up_select_level": "Select level",
  "up_select_role": "Select role",
  "up_choose_accommodation": "Choose your accommodation",
  "up_edit_accommodation": "Edit Accommodation",
  "up_cancel_reservation": "Cancel reservation",
  "up_keep_it": "Keep it",
  "up_no_accommodation": "No accommodation is available for your pass right now.",
  "up_no_units": "No units available right now for this accommodation.",
  "up_occupants": "Number of occupants",
  "up_occupants_max": "Number of occupants (max 12)",
  "up_occupant": "Occupant",
  "up_data_occupants": "Data of the occupants",
  "up_full_name": "Full name / Company name",
  "up_tax_id": "Tax ID (NIF/CIF)",
  "up_id_expiry": "ID/Passport expiry date",
  "up_address": "Address",
  "up_to_modify_contact": "To modify this reservation, contact the person responsible for it.",
  "up_choose_bus": "Choose your departure and/or return bus, then save.",
  "up_edit_bus": "Edit Bus",
  "up_cancel_bus": "Cancel bus reservation",
  "up_confirm_cancel_reservation": "Are you sure you want to cancel this bus reservation?",
  "up_menu": "Menu",
  "up_standard": "Standard",
  "up_vegetarian": "Vegetarian",
  "up_allergies": "Allergies or intolerances",
  "up_meals_intro": "Tell us about your menu and any dietary needs.",
  "up_unit": "Unit",
  "up_change_password": "Change password",
  "up_current_password": "Current Password",
  "up_new_password": "New Password",
  "up_confirm_password": "Confirm Password",
  "up_payment_confirmed": "Payment confirmed.",
  "up_payment_new_tab": "The payment page has been opened in a new tab.",
  "up_error_password_fields": "Please complete all password fields.",
  "up_error_select_competition": "Please select a competition.",
  "up_error_select_level": "Please select a level.",
  "up_error_select_role": "Please select a role.",
  "up_edit_competition_entry": "Edit competition entry",
  "up_register_competition": "Register competition",
  "up_standard_menu": "Standard Menu",
  "up_vegetarian_menu": "Vegetarian Menu",
  "up_not_set": "Not set",
  "up_departure": "Departure",
  "up_return": "Return"
}
'@, [System.Text.Encoding]::new(65001, $false))
Write-Host "OK: en.json"

[System.IO.File]::WriteAllText("$i18n\es.json", @'
{
  "loading": "Cargando...",
  "Loading": "Cargando...",
  "registration_unavailable": "Inscripción no disponible",
  "payment_success": "¡Pago completado!",
  "payment_failed": "El pago ha fallado",
  "registration_confirmed": "Tu inscripción está confirmada. Revisa tu correo electrónico.",
  "registration_submitted": "¡Inscripción enviada!",
  "go_to_login": "Ir al acceso",
  "personal_details": "Datos personales",
  "name": "Nombre",
  "last_names": "Apellidos",
  "email": "Correo electrónico",
  "password": "Contraseña",
  "phone_number": "Teléfono",
  "country": "País",
  "city": "Ciudad",
  "select_pass": "Selecciona tu pase",
  "choose_parties": "Elige tus fiestas",
  "select_level": "Selecciona tu nivel",
  "select_role": "Selecciona tu rol",
  "register_with_partner": "¿Te inscribes con pareja?",
  "yes": "Sí",
  "no": "No",
  "partner_email": "Email de tu pareja",
  "group_code": "Nombre de grupo / código de descuento",
  "select_payment": "Selecciona el tipo de pago",
  "payment_split": "Pago dividido: paga el 50% ahora y el 50% restante en 30 días",
  "total_now": "Importe total a pagar online ahora",
  "total_deferred": "Importe total a pagar en los 10 días siguientes a la confirmación",
  "price": "Precio:",
  "pay_now": "Pagar ahora:",
  "accept_terms": "Acepto los",
  "terms": "Términos y condiciones",
  "submit": "Inscribirse",
  "error_required_fields": "Por favor, completa todos los campos obligatorios.",
  "error_accept_terms": "Debes aceptar los Términos y Condiciones para continuar.",
  "error_select_pass": "Por favor, selecciona un pase para continuar.",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "role_individual": "Individual",
  "up_registration": "Inscripción",
  "up_payment": "Pago",
  "up_competitions": "Competiciones",
  "up_invoices": "Facturas",
  "up_accommodation": "Alojamiento",
  "up_meals": "Comidas",
  "up_buses": "Autobuses",
  "up_personal_details": "Mis datos personales",
  "up_update_profile": "Actualiza tus datos personales.",
  "up_first_name": "Nombre",
  "up_last_name": "Apellidos",
  "up_email": "Tu correo electrónico",
  "up_phone": "Teléfono",
  "up_country": "País",
  "up_city": "Ciudad",
  "up_document": "Número de documento",
  "up_postal_code": "Código postal",
  "up_birth_date": "Fecha de nacimiento",
  "up_save": "Guardar",
  "up_discard": "Descartar",
  "up_edit": "Editar",
  "up_cancel": "Cancelar",
  "up_my_registration": "Mi inscripción",
  "up_pass": "Pase",
  "up_level": "Nivel",
  "up_role": "Rol",
  "up_partner": "Pareja",
  "up_status": "Estado",
  "up_amount": "Importe",
  "up_date": "Fecha",
  "up_pay_registration": "Paga tu inscripción.",
  "up_registration_payment": "Pago de inscripción",
  "up_final_price": "Precio final",
  "up_discount_code": "Código de descuento",
  "up_create_invoice": "Crear factura",
  "up_invoice": "Factura",
  "up_no_invoices": "Aún no hay facturas disponibles.",
  "up_actions": "Acciones",
  "up_competition": "Competición",
  "up_no_competition": "No estás inscrito en ninguna competición.",
  "up_delete_competition": "Eliminar competición",
  "up_no_spots": "No hay plazas disponibles",
  "up_select_competition": "Selecciona una competición",
  "up_select_level": "Selecciona un nivel",
  "up_select_role": "Selecciona un rol",
  "up_choose_accommodation": "Elige tu alojamiento",
  "up_edit_accommodation": "Editar alojamiento",
  "up_cancel_reservation": "Cancelar reserva",
  "up_keep_it": "Mantener",
  "up_no_accommodation": "No hay alojamiento disponible para tu pase en este momento.",
  "up_no_units": "No hay unidades disponibles para este alojamiento en este momento.",
  "up_occupants": "Número de ocupantes",
  "up_occupants_max": "Número de ocupantes (máx. 12)",
  "up_occupant": "Ocupante",
  "up_data_occupants": "Datos de los ocupantes",
  "up_full_name": "Nombre completo / Razón social",
  "up_tax_id": "NIF/CIF",
  "up_id_expiry": "Fecha de caducidad del documento",
  "up_address": "Dirección",
  "up_to_modify_contact": "Para modificar esta reserva, contacta con el responsable.",
  "up_choose_bus": "Elige tu autobús de ida y/o vuelta y guarda.",
  "up_edit_bus": "Editar autobús",
  "up_cancel_bus": "Cancelar reserva de autobús",
  "up_confirm_cancel_reservation": "¿Seguro que quieres cancelar esta reserva de autobús?",
  "up_menu": "Menú",
  "up_standard": "Estándar",
  "up_vegetarian": "Vegetariano",
  "up_allergies": "Alergias o intolerancias",
  "up_meals_intro": "Cuéntanos tus preferencias de menú y necesidades dietéticas.",
  "up_unit": "Unidad",
  "up_change_password": "Cambiar contraseña",
  "up_current_password": "Contraseña actual",
  "up_new_password": "Nueva contraseña",
  "up_confirm_password": "Confirmar contraseña",
  "up_payment_confirmed": "Pago confirmado.",
  "up_payment_new_tab": "La página de pago se ha abierto en una nueva pestaña.",
  "up_error_password_fields": "Por favor, completa todos los campos de contraseña.",
  "up_error_select_competition": "Por favor, selecciona una competición.",
  "up_error_select_level": "Por favor, selecciona un nivel.",
  "up_error_select_role": "Por favor, selecciona un rol.",
  "up_edit_competition_entry": "Editar inscripción a competición",
  "up_register_competition": "Inscribirse a competición",
  "up_standard_menu": "Menú estándar",
  "up_vegetarian_menu": "Menú vegetariano",
  "up_not_set": "No establecido",
  "up_departure": "Ida",
  "up_return": "Vuelta"
}
'@, [System.Text.Encoding]::new(65001, $false))
Write-Host "OK: es.json"

[System.IO.File]::WriteAllText("$i18n\fr.json", @'
{
  "loading": "Chargement...",
  "Loading": "Chargement...",
  "registration_unavailable": "Inscription non disponible",
  "payment_success": "Paiement effectué !",
  "payment_failed": "Échec du paiement",
  "registration_confirmed": "Votre inscription est confirmée. Consultez votre e-mail pour plus de détails.",
  "registration_submitted": "Inscription envoyée !",
  "go_to_login": "Aller à la connexion",
  "personal_details": "Coordonnées personnelles",
  "name": "Prénom",
  "last_names": "Nom de famille",
  "email": "Adresse e-mail",
  "password": "Mot de passe",
  "phone_number": "Téléphone",
  "country": "Pays",
  "city": "Ville",
  "select_pass": "Choisissez votre pass",
  "choose_parties": "Choisissez vos soirées",
  "select_level": "Choisissez votre niveau",
  "select_role": "Choisissez votre rôle",
  "register_with_partner": "Vous inscrivez-vous avec un partenaire ?",
  "yes": "Oui",
  "no": "Non",
  "partner_email": "E-mail de votre partenaire",
  "group_code": "Nom du groupe / code de réduction",
  "select_payment": "Choisissez votre mode de paiement",
  "payment_split": "Paiement en deux fois : payez 50 % maintenant et les 50 % restants dans 30 jours",
  "total_now": "Montant total à payer en ligne maintenant",
  "total_deferred": "Montant total à payer dans les 10 jours suivant la confirmation",
  "price": "Prix :",
  "pay_now": "Payer maintenant :",
  "accept_terms": "J'accepte les",
  "terms": "Conditions générales",
  "submit": "S'inscrire",
  "error_required_fields": "Veuillez remplir tous les champs obligatoires.",
  "error_accept_terms": "Vous devez accepter les conditions générales pour continuer.",
  "error_select_pass": "Veuillez sélectionner un pass pour continuer.",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "role_individual": "Individuel",
  "up_registration": "Inscription",
  "up_payment": "Paiement",
  "up_competitions": "Compétitions",
  "up_invoices": "Factures",
  "up_accommodation": "Hébergement",
  "up_meals": "Repas",
  "up_buses": "Bus",
  "up_personal_details": "Mes coordonnées",
  "up_update_profile": "Mettez à jour vos coordonnées.",
  "up_first_name": "Prénom",
  "up_last_name": "Nom",
  "up_email": "Votre e-mail",
  "up_phone": "Téléphone",
  "up_country": "Pays",
  "up_city": "Ville",
  "up_document": "Numéro de document",
  "up_postal_code": "Code postal",
  "up_birth_date": "Date de naissance",
  "up_save": "Enregistrer",
  "up_discard": "Annuler",
  "up_edit": "Modifier",
  "up_cancel": "Annuler",
  "up_my_registration": "Mon inscription",
  "up_pass": "Pass",
  "up_level": "Niveau",
  "up_role": "Rôle",
  "up_partner": "Partenaire",
  "up_status": "Statut",
  "up_amount": "Montant",
  "up_date": "Date",
  "up_pay_registration": "Payez votre inscription.",
  "up_registration_payment": "Paiement de l'inscription",
  "up_final_price": "Prix final",
  "up_discount_code": "Code de réduction",
  "up_create_invoice": "Créer une facture",
  "up_invoice": "Facture",
  "up_no_invoices": "Aucune facture disponible pour le moment.",
  "up_actions": "Actions",
  "up_competition": "Compétition",
  "up_no_competition": "Vous n'êtes inscrit à aucune compétition.",
  "up_delete_competition": "Supprimer la compétition",
  "up_no_spots": "Aucune place disponible",
  "up_select_competition": "Sélectionner une compétition",
  "up_select_level": "Sélectionner un niveau",
  "up_select_role": "Sélectionner un rôle",
  "up_choose_accommodation": "Choisissez votre hébergement",
  "up_edit_accommodation": "Modifier l'hébergement",
  "up_cancel_reservation": "Annuler la réservation",
  "up_keep_it": "Conserver",
  "up_no_accommodation": "Aucun hébergement disponible pour votre pass en ce moment.",
  "up_no_units": "Aucune unité disponible pour cet hébergement en ce moment.",
  "up_occupants": "Nombre d'occupants",
  "up_occupants_max": "Nombre d'occupants (max. 12)",
  "up_occupant": "Occupant",
  "up_data_occupants": "Données des occupants",
  "up_full_name": "Nom complet / Raison sociale",
  "up_tax_id": "Numéro fiscal",
  "up_id_expiry": "Date d'expiration du document",
  "up_address": "Adresse",
  "up_to_modify_contact": "Pour modifier cette réservation, contactez la personne responsable.",
  "up_choose_bus": "Choisissez votre bus aller et/ou retour, puis enregistrez.",
  "up_edit_bus": "Modifier le bus",
  "up_cancel_bus": "Annuler la réservation de bus",
  "up_confirm_cancel_reservation": "Êtes-vous sûr de vouloir annuler cette réservation de bus ?",
  "up_menu": "Menu",
  "up_standard": "Standard",
  "up_vegetarian": "Végétarien",
  "up_allergies": "Allergies ou intolérances",
  "up_meals_intro": "Indiquez vos préférences de menu et besoins alimentaires.",
  "up_unit": "Unité",
  "up_change_password": "Changer le mot de passe",
  "up_current_password": "Mot de passe actuel",
  "up_new_password": "Nouveau mot de passe",
  "up_confirm_password": "Confirmer le mot de passe",
  "up_payment_confirmed": "Paiement confirmé.",
  "up_payment_new_tab": "La page de paiement a été ouverte dans un nouvel onglet.",
  "up_error_password_fields": "Veuillez compléter tous les champs du mot de passe.",
  "up_error_select_competition": "Veuillez sélectionner une compétition.",
  "up_error_select_level": "Veuillez sélectionner un niveau.",
  "up_error_select_role": "Veuillez sélectionner un rôle.",
  "up_edit_competition_entry": "Modifier l'inscription à la compétition",
  "up_register_competition": "S'inscrire à la compétition",
  "up_standard_menu": "Menu standard",
  "up_vegetarian_menu": "Menu végétarien",
  "up_not_set": "Non défini",
  "up_departure": "Aller",
  "up_return": "Retour"
}
'@, [System.Text.Encoding]::new(65001, $false))
Write-Host "OK: fr.json"

[System.IO.File]::WriteAllText("$i18n\ca.json", @'
{
  "loading": "Carregant...",
  "Loading": "Carregant...",
  "registration_unavailable": "Inscripció no disponible",
  "payment_success": "Pagament completat!",
  "payment_failed": "El pagament ha fallat",
  "registration_confirmed": "La teva inscripció està confirmada. Revisa el teu correu electrònic.",
  "registration_submitted": "Inscripció enviada!",
  "go_to_login": "Anar a l'accés",
  "personal_details": "Dades personals",
  "name": "Nom",
  "last_names": "Cognoms",
  "email": "Correu electrònic",
  "password": "Contrasenya",
  "phone_number": "Telèfon",
  "country": "País",
  "city": "Ciutat",
  "select_pass": "Selecciona el teu passi",
  "choose_parties": "Tria les teves festes",
  "select_level": "Selecciona el teu nivell",
  "select_role": "Selecciona el teu rol",
  "register_with_partner": "Et vols inscriure amb parella?",
  "yes": "Sí",
  "no": "No",
  "partner_email": "Email de la teva parella",
  "group_code": "Nom del grup / codi de descompte",
  "select_payment": "Selecciona el tipus de pagament",
  "payment_split": "Pagament dividit: paga el 50% ara i el 50% restant en 30 dies",
  "total_now": "Import total a pagar en línia ara",
  "total_deferred": "Import total a pagar en els 10 dies següents a la confirmació",
  "price": "Preu:",
  "pay_now": "Pagar ara:",
  "accept_terms": "Accepto els",
  "terms": "Termes i condicions",
  "submit": "Inscriure's",
  "error_required_fields": "Si us plau, completa tots els camps obligatoris.",
  "error_accept_terms": "Has d'acceptar els Termes i Condicions per continuar.",
  "error_select_pass": "Si us plau, selecciona un passi per continuar.",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "role_individual": "Individual",
  "up_registration": "Inscripció",
  "up_payment": "Pagament",
  "up_competitions": "Competicions",
  "up_invoices": "Factures",
  "up_accommodation": "Allotjament",
  "up_meals": "Àpats",
  "up_buses": "Autobusos",
  "up_personal_details": "Les meves dades personals",
  "up_update_profile": "Actualitza les teves dades personals.",
  "up_first_name": "Nom",
  "up_last_name": "Cognoms",
  "up_email": "El teu correu electrònic",
  "up_phone": "Telèfon",
  "up_country": "País",
  "up_city": "Ciutat",
  "up_document": "Número de document",
  "up_postal_code": "Codi postal",
  "up_birth_date": "Data de naixement",
  "up_save": "Desar",
  "up_discard": "Descartar",
  "up_edit": "Editar",
  "up_cancel": "Cancel·lar",
  "up_my_registration": "La meva inscripció",
  "up_pass": "Passi",
  "up_level": "Nivell",
  "up_role": "Rol",
  "up_partner": "Parella",
  "up_status": "Estat",
  "up_amount": "Import",
  "up_date": "Data",
  "up_pay_registration": "Paga la teva inscripció.",
  "up_registration_payment": "Pagament de la inscripció",
  "up_final_price": "Preu final",
  "up_discount_code": "Codi de descompte",
  "up_create_invoice": "Crear factura",
  "up_invoice": "Factura",
  "up_no_invoices": "Encara no hi ha factures disponibles.",
  "up_actions": "Accions",
  "up_competition": "Competició",
  "up_no_competition": "No estàs inscrit a cap competició.",
  "up_delete_competition": "Eliminar competició",
  "up_no_spots": "No hi ha places disponibles",
  "up_select_competition": "Selecciona una competició",
  "up_select_level": "Selecciona un nivell",
  "up_select_role": "Selecciona un rol",
  "up_choose_accommodation": "Tria el teu allotjament",
  "up_edit_accommodation": "Editar allotjament",
  "up_cancel_reservation": "Cancel·lar reserva",
  "up_keep_it": "Mantenir",
  "up_no_accommodation": "No hi ha allotjament disponible per al teu passi en aquest moment.",
  "up_no_units": "No hi ha unitats disponibles per a aquest allotjament en aquest moment.",
  "up_occupants": "Nombre d'ocupants",
  "up_occupants_max": "Nombre d'ocupants (màx. 12)",
  "up_occupant": "Ocupant",
  "up_data_occupants": "Dades dels ocupants",
  "up_full_name": "Nom complet / Raó social",
  "up_tax_id": "NIF/CIF",
  "up_id_expiry": "Data de caducitat del document",
  "up_address": "Adreça",
  "up_to_modify_contact": "Per modificar aquesta reserva, contacta amb el responsable.",
  "up_choose_bus": "Tria el teu autobús d'anada i/o tornada i desa.",
  "up_edit_bus": "Editar autobús",
  "up_cancel_bus": "Cancel·lar reserva d'autobús",
  "up_confirm_cancel_reservation": "Estàs segur que vols cancel·lar aquesta reserva d'autobús?",
  "up_menu": "Menú",
  "up_standard": "Estàndard",
  "up_vegetarian": "Vegetarià",
  "up_allergies": "Al·lèrgies o intoleràncies",
  "up_meals_intro": "Explica'ns les teves preferències de menú i necessitats dietètiques.",
  "up_unit": "Unitat",
  "up_change_password": "Canviar contrasenya",
  "up_current_password": "Contrasenya actual",
  "up_new_password": "Nova contrasenya",
  "up_confirm_password": "Confirmar contrasenya",
  "up_payment_confirmed": "Pagament confirmat.",
  "up_payment_new_tab": "La pàgina de pagament s'ha obert en una nova pestanya.",
  "up_error_password_fields": "Si us plau, completa tots els camps de la contrasenya.",
  "up_error_select_competition": "Si us plau, selecciona una competició.",
  "up_error_select_level": "Si us plau, selecciona un nivell.",
  "up_error_select_role": "Si us plau, selecciona un rol.",
  "up_edit_competition_entry": "Editar inscripció a la competició",
  "up_register_competition": "Inscriure's a la competició",
  "up_standard_menu": "Menú estàndard",
  "up_vegetarian_menu": "Menú vegetarià",
  "up_not_set": "No establert",
  "up_departure": "Anada",
  "up_return": "Tornada"
}
'@, [System.Text.Encoding]::new(65001, $false))
Write-Host "OK: ca.json"

Write-Host ""
Write-Host "Done. All 4 JSON files rewritten with complete key sets."
Write-Host "Restart the app and test all languages."