# fix_i18n_add_missing.ps1
# Sobreescribe los 4 JSONs con el contenido original MAS los 55 keys que faltan
# Ejecutar desde la raiz del repo: .\tools\fix_i18n_add_missing.ps1

$ErrorActionPreference = "Stop"
$i18n = "Alakai.FestivalManager.Admin\wwwroot\i18n"
if (-not (Test-Path $i18n)) { Write-Error "ABORT: No se encuentra $i18n"; exit 1 }

function Write-Json { param([string]$File, [string]$Content)
    $path = Join-Path $i18n $File
    [System.IO.File]::WriteAllText($path, $Content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "OK: $File"
}

Write-Json "en.json" @'
{
  "loading": "Loading...",
  "registration_unavailable": "Registration unavailable",
  "personal_details": "Personal Details",
  "name": "Name",
  "last_names": "Last Names",
  "email": "Email",
  "phone_number": "Phone Number",
  "country": "Country",
  "city": "City",
  "password": "Password",
  "select_your_pass": "Select your pass",
  "select_your_level": "Select your level",
  "select_your_role": "Select your role",
  "leader": "Leader",
  "follower": "Follower",
  "individual": "Individual",
  "are_you_registering_with_partner": "Are you registering with a partner?",
  "partner_email": "Partner's email",
  "group_name_discount_code": "Group name / discount code",
  "group_name": "Group name",
  "choose_your_parties": "Choose your party/ies",
  "select_payment_type": "Select payment type",
  "full_payment_now": "Full payment now",
  "split_payment": "Split payment: pay 50% online now and the remaining 50% in 30 days",
  "deferred_payment": "Total amount due within 10 days of receiving the confirmation email",
  "price": "Price:",
  "total_amount_online": "Total amount to pay online now",
  "i_accept_the": "I accept the",
  "terms_conditions": "Terms & Conditions",
  "pay_now": "Pay now:",
  "complete_required_fields": "Please complete all required fields.",
  "select_pass_to_continue": "Please select a pass to continue.",
  "accept_terms": "You must accept the Terms and Conditions to continue.",
  "registration_confirmed": "Your registration is confirmed. Check your email for details.",
  "registration_submitted": "Registration submitted!",
  "payment_completed": "Payment completed!",
  "payment_failed": "Payment failed",
  "go_to_login": "Go to login",
  "dashboard": "Dashboard",
  "my_registration": "My Registration details",
  "my_personal_details": "My personal details",
  "update_personal_details": "Update your personal details.",
  "first_name": "First Name",
  "last_name": "Last Name",
  "document_number": "Document Number",
  "id_passport_expiry": "ID/Passport expiry date",
  "birth_date": "Birth date",
  "postal_code": "Postal code",
  "tax_id": "Tax ID (NIF/CIF)",
  "full_name_company": "Full name / Company name",
  "address": "Address",
  "save": "Save",
  "discard": "Discard",
  "cancel": "Cancel",
  "edit": "Edit",
  "payment": "Payment",
  "payments": "Payments",
  "pay_your_registration": "Pay your registration.",
  "registration_payment": "Registration Payment",
  "final_price": "Final Price",
  "amount": "Amount",
  "date": "Date",
  "status": "Status",
  "pass": "Pass",
  "level": "Level",
  "role": "Role",
  "partner": "Partner",
  "discount_code": "Discount Code",
  "invoice": "Invoice",
  "invoices": "Invoices",
  "create_invoice": "Create Invoice",
  "no_invoices": "There are no invoices available yet.",
  "accommodation": "Accommodation",
  "choose_accommodation": "Choose your accommodation",
  "no_accommodation_available": "No accommodation is available for your pass right now.",
  "no_units_available": "No units available right now for this accommodation.",
  "number_of_occupants": "Number of occupants",
  "number_of_occupants_max": "Number of occupants (max 12)",
  "data_of_occupants": "Data of the occupants",
  "occupant": "Occupant",
  "unit": "Unit",
  "edit_accommodation": "Edit Accommodation",
  "cancel_reservation": "Cancel reservation",
  "to_modify_contact_responsible": "To modify this reservation, contact the person responsible for it.",
  "buses": "Buses",
  "choose_bus": "Choose your departure and/or return bus, then save.",
  "no_spots_available": "No spots available",
  "edit_bus": "Edit Bus",
  "cancel_bus_reservation": "Cancel bus reservation",
  "confirm_cancel_bus": "Are you sure you want to cancel this bus reservation?",
  "keep_it": "Keep it",
  "meals": "Meals",
  "tell_us_menu": "Tell us about your menu and any dietary needs.",
  "menu": "Menu",
  "standard": "Standard",
  "vegetarian": "Vegetarian",
  "allergies": "Allergies or intolerances",
  "is_celiac": "Celiac / Gluten intolerant",
  "competitions": "Competitions",
  "competition": "Competition",
  "select_competition": "Select competition",
  "select_level": "Select level",
  "select_role": "Select role",
  "not_registered_competition": "You are not registered to any competition.",
  "delete_competition": "Delete competition",
  "confirm_delete_competition": "Are you sure you want to delete your registration to",
  "actions": "Actions",
  "change_password": "Change password",
  "current_password": "Current Password",
  "new_password": "New Password",
  "confirm_password": "Confirm Password",
  "your_email": "Your email",
  "register": "Register",
  "payment_required": "You must complete at least a partial payment for your registration before making this reservation.",
  "Loading": "Loading...",
  "choose_parties": "Choose your party/ies",
  "error_accept_terms": "You must accept the Terms and Conditions to continue.",
  "error_required_fields": "Please complete all required fields.",
  "error_select_pass": "Please select a pass to continue.",
  "group_code": "Group name / discount code",
  "payment_split": "Split payment: pay 50% online now and the remaining 50% in 30 days",
  "payment_success": "Payment completed!",
  "register_with_partner": "Are you registering with a partner?",
  "select_pass": "Select your pass",
  "select_payment": "Select payment type",
  "submit": "Register",
  "terms": "Terms & Conditions",
  "total_deferred": "Total amount due within 10 days of receiving the confirmation email",
  "total_now": "Total amount to pay online now",
  "yes": "Yes",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "up_accommodation": "Accommodation",
  "up_actions": "Actions",
  "up_address": "Address",
  "up_allergies": "Allergies or intolerances",
  "up_amount": "Amount",
  "up_birth_date": "Birth date",
  "up_buses": "Buses",
  "up_cancel": "Cancel",
  "up_cancel_bus": "Cancel bus reservation",
  "up_cancel_reservation": "Cancel reservation",
  "up_change_password": "Change password",
  "up_choose_accommodation": "Choose your accommodation",
  "up_choose_bus": "Choose your departure and/or return bus, then save.",
  "up_city": "City",
  "up_competition": "Competition",
  "up_competitions": "Competitions",
  "up_confirm_cancel_reservation": "Are you sure you want to cancel this reservation?",
  "up_confirm_password": "Confirm Password",
  "up_country": "Country",
  "up_create_invoice": "Create Invoice",
  "up_current_password": "Current Password",
  "up_data_occupants": "Data of the occupants",
  "up_date": "Date",
  "up_delete_competition": "Delete competition",
  "up_departure": "Departure",
  "up_discount_code": "Discount Code",
  "up_document": "Document Number",
  "up_edit_accommodation": "Edit Accommodation",
  "up_edit_bus": "Edit Bus",
  "up_edit_competition_entry": "Edit competition entry",
  "up_email": "Your email",
  "up_error_password_fields": "Please complete all password fields.",
  "up_error_select_competition": "Please select a competition.",
  "up_error_select_level": "Please select a level.",
  "up_error_select_role": "Please select a role.",
  "up_final_price": "Final Price",
  "up_first_name": "First Name",
  "up_full_name": "Full name / Company name",
  "up_id_expiry": "ID/Passport expiry date",
  "up_invoice": "Invoice",
  "up_invoices": "Invoices",
  "up_keep_it": "Keep it",
  "up_last_name": "Last Name",
  "up_level": "Level",
  "up_meals": "Meals",
  "up_meals_intro": "Tell us about your menu and any dietary needs.",
  "up_menu": "Menu",
  "up_my_registration": "My Registration",
  "up_new_password": "New Password",
  "up_no_accommodation": "No accommodation is available for your pass right now.",
  "up_no_competition": "You are not registered to any competition.",
  "up_no_invoices": "There are no invoices available yet.",
  "up_no_spots": "No spots available",
  "up_no_units": "No units available right now for this accommodation.",
  "up_not_set": "Not set",
  "up_occupant": "Occupant",
  "up_occupants": "Number of occupants",
  "up_occupants_max": "Number of occupants (max 12)",
  "up_partner": "Partner",
  "up_pass": "Pass",
  "up_pay_registration": "Pay your registration.",
  "up_payment": "Payment",
  "up_payment_confirmed": "Payment confirmed.",
  "up_payment_new_tab": "The payment page has been opened in a new tab.",
  "up_personal_details": "My personal details",
  "up_phone": "Phone",
  "up_postal_code": "Postal code",
  "up_register_competition": "Register competition",
  "up_registration": "Registration",
  "up_registration_payment": "Registration Payment",
  "up_role": "Role",
  "up_select_competition": "Select competition",
  "up_select_level": "Select level",
  "up_select_role": "Select role",
  "up_standard": "Standard",
  "up_standard_menu": "Standard Menu",
  "up_status": "Status",
  "up_tax_id": "Tax ID (NIF/CIF)",
  "up_to_modify_contact": "To modify this reservation, contact the person responsible for it.",
  "up_unit": "Unit",
  "up_update_profile": "Update your personal details.",
  "up_vegetarian": "Vegetarian",
  "up_vegetarian_menu": "Vegetarian Menu",
  "reg_all_levels_discount": "discount applied for selecting all parties",
  "reg_code_not_found": "Code not found.",
  "reg_discount_applied": "Group discount applied",
  "reg_discount_pending": "The group has not yet reached the minimum number of participants. The discount will be applied automatically once the minimum is reached.",
  "reg_management_fee": "for management fee",
  "reg_no_solo_spots": "There are no solo spots available for this role at this level. You must register with a partner or choose another level.",
  "reg_of_50": "of the 50%",
  "reg_of_total": "of the total",
  "reg_partner_found": "Your partner is already registered. You will be linked together.",
  "reg_partner_not_found": "Your partner is not registered yet. You can register separately and will be linked once your partner registers.",
  "reg_payment_failed_body": "Your registration was created but the payment was not completed. You can try again from the User Panel.",
  "reg_submitted_body": "Check your email for confirmation. You have 10 days to complete your payment from the User Panel.",
  "up_accommodation_reserved": "Accommodation reservation created successfully.",
  "up_accommodation_updated": "Accommodation reservation updated successfully.",
  "up_booked": "Booked",
  "up_booked_in": "You are booked in",
  "up_bus_cancelled": "Bus reservation cancelled successfully.",
  "up_bus_reserved": "Bus reservation created successfully.",
  "up_bus_updated": "Bus reservation updated successfully.",
  "up_cancelling": "Cancelling...",
  "up_celiac": "Celiac",
  "up_competition_created": "Competition entry created successfully.",
  "up_competition_deleted": "Competition entry deleted successfully.",
  "up_competition_updated": "Competition entry updated successfully.",
  "up_confirm_cancel_accommodation": "Are you sure you want to cancel this accommodation reservation? This cannot be undone.",
  "up_confirm_delete_competition": "Are you sure you want to delete your registration to",
  "up_creating": "Creating...",
  "up_delete": "Delete",
  "up_deleting": "Deleting...",
  "up_due": "Due",
  "up_enter_billing_details": "Enter your billing details.",
  "up_is_celiac": "I am Celiac or gluten intolerant",
  "up_meal_saved": "Meal preference saved successfully.",
  "up_no_partner": "No assigned partner",
  "up_not_booked": "Not booked",
  "up_paid": "paid",
  "up_password_change_error": "Password could not be changed.",
  "up_password_changed": "Password changed successfully.",
  "up_password_mismatch": "New password and confirmation do not match.",
  "up_pay_now": "Pay now",
  "up_pay_remaining": "Pay remaining",
  "up_payment_required": "You must complete at least a partial payment for your registration before making this reservation.",
  "up_pending": "pending",
  "up_people": "people",
  "up_person": "person",
  "up_plan_deferred": "Deferred - Pay within 10 days",
  "up_plan_full": "Full payment",
  "up_plan_split": "Split - 50% now, 50% in 30 days",
  "up_profile_save_error": "Profile could not be saved.",
  "up_profile_saved": "Profile saved successfully.",
  "up_reservation_cancelled": "Reservation cancelled successfully.",
  "up_responsible": "responsible",
  "up_save_changes": "Save changes",
  "up_saving": "Saving...",
  "up_select_competition_details": "Select your competition details."
}
'@

Write-Json "es.json" @'
{
  "loading": "Cargando...",
  "registration_unavailable": "Inscripción no disponible",
  "personal_details": "Datos personales",
  "name": "Nombre",
  "last_names": "Apellidos",
  "email": "Correo electrónico",
  "phone_number": "Teléfono",
  "country": "País",
  "city": "Ciudad",
  "password": "Contraseña",
  "select_your_pass": "Selecciona tu pase",
  "select_your_level": "Selecciona tu nivel",
  "select_your_role": "Selecciona tu rol",
  "leader": "Líder",
  "follower": "Seguidor/a",
  "individual": "Individual",
  "are_you_registering_with_partner": "¿Te inscribes con pareja?",
  "partner_email": "Email de tu pareja",
  "group_name_discount_code": "Nombre de grupo / código de descuento",
  "group_name": "Nombre de grupo",
  "choose_your_parties": "Elige tu/s fiesta/s",
  "select_payment_type": "Selecciona el tipo de pago",
  "full_payment_now": "Pago completo ahora",
  "split_payment": "Pago fraccionado: paga el 50% ahora y el 50% restante en 30 días",
  "deferred_payment": "Importe total a pagar en los 10 días siguientes a recibir el email de confirmación",
  "price": "Precio:",
  "total_amount_online": "Importe total a pagar online ahora",
  "i_accept_the": "Acepto los",
  "terms_conditions": "Términos y Condiciones",
  "pay_now": "Pagar ahora:",
  "complete_required_fields": "Por favor, completa todos los campos obligatorios.",
  "select_pass_to_continue": "Por favor, selecciona un pase para continuar.",
  "accept_terms": "Debes aceptar los Términos y Condiciones para continuar.",
  "registration_confirmed": "Tu inscripción está confirmada. Revisa tu correo electrónico.",
  "registration_submitted": "¡Inscripción enviada!",
  "payment_completed": "¡Pago completado!",
  "payment_failed": "Pago fallido",
  "go_to_login": "Ir al inicio de sesión",
  "dashboard": "Panel",
  "my_registration": "Mi inscripción",
  "my_personal_details": "Mis datos personales",
  "update_personal_details": "Actualiza tus datos personales.",
  "first_name": "Nombre",
  "last_name": "Apellidos",
  "document_number": "Número de documento",
  "id_passport_expiry": "Fecha de caducidad del DNI/Pasaporte",
  "birth_date": "Fecha de nacimiento",
  "postal_code": "Código postal",
  "tax_id": "NIF/CIF",
  "full_name_company": "Nombre completo / Nombre de empresa",
  "address": "Dirección",
  "save": "Guardar",
  "discard": "Descartar",
  "cancel": "Cancelar",
  "edit": "Editar",
  "payment": "Pago",
  "payments": "Pagos",
  "pay_your_registration": "Paga tu inscripción.",
  "registration_payment": "Pago de inscripción",
  "final_price": "Precio final",
  "amount": "Importe",
  "date": "Fecha",
  "status": "Estado",
  "pass": "Pase",
  "level": "Nivel",
  "role": "Rol",
  "partner": "Pareja",
  "discount_code": "Código de descuento",
  "invoice": "Factura",
  "invoices": "Facturas",
  "create_invoice": "Crear factura",
  "no_invoices": "Todavía no hay facturas disponibles.",
  "accommodation": "Alojamiento",
  "choose_accommodation": "Elige tu alojamiento",
  "no_accommodation_available": "No hay alojamiento disponible para tu pase en este momento.",
  "no_units_available": "No hay unidades disponibles para este alojamiento en este momento.",
  "number_of_occupants": "Número de ocupantes",
  "number_of_occupants_max": "Número de ocupantes (máx. 12)",
  "data_of_occupants": "Datos de los ocupantes",
  "occupant": "Ocupante",
  "unit": "Unidad",
  "edit_accommodation": "Editar alojamiento",
  "cancel_reservation": "Cancelar reserva",
  "to_modify_contact_responsible": "Para modificar esta reserva, contacta con el responsable.",
  "buses": "Autobuses",
  "choose_bus": "Elige tu autobús de ida y/o vuelta y guarda.",
  "no_spots_available": "Sin plazas disponibles",
  "edit_bus": "Editar autobús",
  "cancel_bus_reservation": "Cancelar reserva de autobús",
  "confirm_cancel_bus": "¿Seguro que quieres cancelar esta reserva de autobús?",
  "keep_it": "Mantener",
  "meals": "Comidas",
  "tell_us_menu": "Cuéntanos tu menú y necesidades dietéticas.",
  "menu": "Menú",
  "standard": "Estándar",
  "vegetarian": "Vegetariano",
  "allergies": "Alergias o intolerancias",
  "is_celiac": "Celíaco/a / Intolerante al gluten",
  "competitions": "Competiciones",
  "competition": "Competición",
  "select_competition": "Seleccionar competición",
  "select_level": "Seleccionar nivel",
  "select_role": "Seleccionar rol",
  "not_registered_competition": "No estás inscrito en ninguna competición.",
  "delete_competition": "Eliminar competición",
  "confirm_delete_competition": "¿Seguro que quieres eliminar tu inscripción a",
  "actions": "Acciones",
  "change_password": "Cambiar contraseña",
  "current_password": "Contraseña actual",
  "new_password": "Nueva contraseña",
  "confirm_password": "Confirmar contraseña",
  "your_email": "Tu correo electrónico",
  "register": "Inscribirse",
  "payment_required": "Debes realizar al menos un pago parcial antes de hacer esta reserva.",
  "Loading": "Cargando...",
  "choose_parties": "Elige tus fiestas",
  "error_accept_terms": "Debes aceptar los Términos y Condiciones para continuar.",
  "error_required_fields": "Por favor, completa todos los campos obligatorios.",
  "error_select_pass": "Por favor, selecciona un pase para continuar.",
  "group_code": "Nombre de grupo / código de descuento",
  "payment_split": "Pago dividido: paga el 50% ahora y el 50% restante en 30 días",
  "payment_success": "¡Pago completado!",
  "register_with_partner": "¿Te inscribes con pareja?",
  "select_pass": "Selecciona tu pase",
  "select_payment": "Selecciona el tipo de pago",
  "submit": "Inscribirse",
  "terms": "Términos y condiciones",
  "total_deferred": "Importe total a pagar en los 10 días siguientes a la confirmación",
  "total_now": "Importe total a pagar online ahora",
  "yes": "Sí",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "up_accommodation": "Alojamiento",
  "up_actions": "Acciones",
  "up_address": "Dirección",
  "up_allergies": "Alergias o intolerancias",
  "up_amount": "Importe",
  "up_birth_date": "Fecha de nacimiento",
  "up_buses": "Autobuses",
  "up_cancel": "Cancelar",
  "up_cancel_bus": "Cancelar reserva de autobús",
  "up_cancel_reservation": "Cancelar reserva",
  "up_change_password": "Cambiar contraseña",
  "up_choose_accommodation": "Elige tu alojamiento",
  "up_choose_bus": "Elige tu autobús de ida y/o vuelta y guarda.",
  "up_city": "Ciudad",
  "up_competition": "Competición",
  "up_competitions": "Competiciones",
  "up_confirm_cancel_reservation": "¿Seguro que quieres cancelar esta reserva?",
  "up_confirm_password": "Confirmar contraseña",
  "up_country": "País",
  "up_create_invoice": "Crear factura",
  "up_current_password": "Contraseña actual",
  "up_data_occupants": "Datos de los ocupantes",
  "up_date": "Fecha",
  "up_delete_competition": "Eliminar competición",
  "up_departure": "Ida",
  "up_discount_code": "Código de descuento",
  "up_document": "Número de documento",
  "up_edit_accommodation": "Editar alojamiento",
  "up_edit_bus": "Editar autobús",
  "up_edit_competition_entry": "Editar inscripción a competición",
  "up_email": "Tu correo electrónico",
  "up_error_password_fields": "Por favor, completa todos los campos de contraseña.",
  "up_error_select_competition": "Por favor, selecciona una competición.",
  "up_error_select_level": "Por favor, selecciona un nivel.",
  "up_error_select_role": "Por favor, selecciona un rol.",
  "up_final_price": "Precio final",
  "up_first_name": "Nombre",
  "up_full_name": "Nombre completo / Nombre de empresa",
  "up_id_expiry": "Fecha de caducidad del DNI/Pasaporte",
  "up_invoice": "Factura",
  "up_invoices": "Facturas",
  "up_keep_it": "Mantener",
  "up_last_name": "Apellidos",
  "up_level": "Nivel",
  "up_meals": "Comidas",
  "up_meals_intro": "Cuéntanos tu menú y necesidades dietéticas.",
  "up_menu": "Menú",
  "up_my_registration": "Mi inscripción",
  "up_new_password": "Nueva contraseña",
  "up_no_accommodation": "No hay alojamiento disponible para tu pase en este momento.",
  "up_no_competition": "No estás inscrito en ninguna competición.",
  "up_no_invoices": "Todavía no hay facturas disponibles.",
  "up_no_spots": "Sin plazas disponibles",
  "up_no_units": "No hay unidades disponibles para este alojamiento en este momento.",
  "up_not_set": "No establecido",
  "up_occupant": "Ocupante",
  "up_occupants": "Número de ocupantes",
  "up_occupants_max": "Número de ocupantes (máx. 12)",
  "up_partner": "Pareja",
  "up_pass": "Pase",
  "up_pay_registration": "Paga tu inscripción.",
  "up_payment": "Pago",
  "up_payment_confirmed": "Pago confirmado.",
  "up_payment_new_tab": "La página de pago se ha abierto en una nueva pestaña.",
  "up_personal_details": "Mis datos personales",
  "up_phone": "Teléfono",
  "up_postal_code": "Código postal",
  "up_register_competition": "Inscribirse a competición",
  "up_registration": "Inscripción",
  "up_registration_payment": "Pago de inscripción",
  "up_role": "Rol",
  "up_select_competition": "Seleccionar competición",
  "up_select_level": "Seleccionar nivel",
  "up_select_role": "Seleccionar rol",
  "up_standard": "Estándar",
  "up_standard_menu": "Menú estándar",
  "up_status": "Estado",
  "up_tax_id": "NIF/CIF",
  "up_to_modify_contact": "Para modificar esta reserva, contacta con el responsable.",
  "up_unit": "Unidad",
  "up_update_profile": "Actualiza tus datos personales.",
  "up_vegetarian": "Vegetariano",
  "up_vegetarian_menu": "Menú vegetariano",
  "reg_all_levels_discount": "descuento aplicado por seleccionar todas las fiestas",
  "reg_code_not_found": "Código no encontrado.",
  "reg_discount_applied": "Descuento de grupo aplicado",
  "reg_discount_pending": "El grupo aún no ha alcanzado el número mínimo de participantes. El descuento se aplicará automáticamente cuando se alcance el mínimo.",
  "reg_management_fee": "de comisión de gestión",
  "reg_no_solo_spots": "No hay plazas individuales disponibles para este rol en este nivel. Debes inscribirte con pareja o elegir otro nivel.",
  "reg_of_50": "del 50%",
  "reg_of_total": "del total",
  "reg_partner_found": "Tu pareja ya está inscrita. Quedaréis vinculados/as.",
  "reg_partner_not_found": "Tu pareja aún no está inscrita. Puedes inscribirte por separado y quedaréis vinculados/as cuando tu pareja se inscriba.",
  "reg_payment_failed_body": "Tu inscripción se creó pero el pago no se completó. Puedes intentarlo de nuevo desde el Panel de Usuario.",
  "reg_submitted_body": "Revisa tu correo para la confirmación. Tienes 10 días para completar el pago desde el Panel de Usuario.",
  "up_accommodation_reserved": "Reserva de alojamiento creada correctamente.",
  "up_accommodation_updated": "Reserva de alojamiento actualizada correctamente.",
  "up_booked": "Reservado",
  "up_booked_in": "Estás alojado en",
  "up_bus_cancelled": "Reserva de autobús cancelada correctamente.",
  "up_bus_reserved": "Reserva de autobús creada correctamente.",
  "up_bus_updated": "Reserva de autobús actualizada correctamente.",
  "up_cancelling": "Cancelando...",
  "up_celiac": "Celíaco",
  "up_competition_created": "Inscripción a competición creada correctamente.",
  "up_competition_deleted": "Inscripción a competición eliminada correctamente.",
  "up_competition_updated": "Inscripción a competición actualizada correctamente.",
  "up_confirm_cancel_accommodation": "¿Seguro que quieres cancelar esta reserva de alojamiento? Esta acción no se puede deshacer.",
  "up_confirm_delete_competition": "¿Seguro que quieres eliminar tu inscripción a",
  "up_creating": "Creando...",
  "up_delete": "Eliminar",
  "up_deleting": "Eliminando...",
  "up_due": "Vence",
  "up_enter_billing_details": "Introduce tus datos de facturación.",
  "up_is_celiac": "Soy Celíaco/a o intolerante al gluten",
  "up_meal_saved": "Preferencia de menú guardada correctamente.",
  "up_no_partner": "Sin pareja asignada",
  "up_not_booked": "Sin reserva",
  "up_paid": "pagado",
  "up_password_change_error": "No se pudo cambiar la contraseña.",
  "up_password_changed": "Contraseña cambiada correctamente.",
  "up_password_mismatch": "La nueva contraseña y la confirmación no coinciden.",
  "up_pay_now": "Pagar ahora",
  "up_pay_remaining": "Pagar el resto",
  "up_payment_required": "Debes realizar al menos un pago parcial antes de hacer esta reserva.",
  "up_pending": "pendiente",
  "up_people": "personas",
  "up_person": "persona",
  "up_plan_deferred": "Diferido - Pagar en 10 días",
  "up_plan_full": "Pago completo",
  "up_plan_split": "Fraccionado - 50% ahora, 50% en 30 días",
  "up_profile_save_error": "No se pudo guardar el perfil.",
  "up_profile_saved": "Perfil guardado correctamente.",
  "up_reservation_cancelled": "Reserva cancelada correctamente.",
  "up_responsible": "responsable",
  "up_save_changes": "Guardar cambios",
  "up_saving": "Guardando...",
  "up_select_competition_details": "Selecciona los detalles de la competición."
}
'@

Write-Json "fr.json" @'
{
  "loading": "Chargement...",
  "registration_unavailable": "Inscription non disponible",
  "personal_details": "Informations personnelles",
  "name": "Prénom",
  "last_names": "Nom(s)",
  "email": "Email",
  "phone_number": "Téléphone",
  "country": "Pays",
  "city": "Ville",
  "password": "Mot de passe",
  "select_your_pass": "Choisissez votre pass",
  "select_your_level": "Choisissez votre niveau",
  "select_your_role": "Choisissez votre rôle",
  "leader": "Leader",
  "follower": "Suiveur/se",
  "individual": "Individuel",
  "are_you_registering_with_partner": "Vous inscrivez-vous avec un(e) partenaire ?",
  "partner_email": "Email de votre partenaire",
  "group_name_discount_code": "Nom de groupe / code de réduction",
  "group_name": "Nom de groupe",
  "choose_your_parties": "Choisissez vos soirée(s)",
  "select_payment_type": "Choisissez votre mode de paiement",
  "full_payment_now": "Paiement complet maintenant",
  "split_payment": "Paiement fractionné : payez 50 % maintenant et les 50 % restants dans 30 jours",
  "deferred_payment": "Montant total dû dans les 10 jours suivant la réception de l’email de confirmation",
  "price": "Prix :",
  "total_amount_online": "Montant total à payer en ligne maintenant",
  "i_accept_the": "J’accepte les",
  "terms_conditions": "Conditions Générales",
  "pay_now": "Payer maintenant :",
  "complete_required_fields": "Veuillez compléter tous les champs obligatoires.",
  "select_pass_to_continue": "Veuillez sélectionner un pass pour continuer.",
  "accept_terms": "Vous devez accepter les Conditions Générales pour continuer.",
  "registration_confirmed": "Votre inscription est confirmée. Vérifiez vos emails pour les détails.",
  "registration_submitted": "Inscription envoyée !",
  "payment_completed": "Paiement effectué !",
  "payment_failed": "Paiement échoué",
  "go_to_login": "Aller à la connexion",
  "dashboard": "Tableau de bord",
  "my_registration": "Mon inscription",
  "my_personal_details": "Mes informations personnelles",
  "update_personal_details": "Mettez à jour vos informations personnelles.",
  "first_name": "Prénom",
  "last_name": "Nom",
  "document_number": "Numéro de document",
  "id_passport_expiry": "Date d’expiration CNI/Passeport",
  "birth_date": "Date de naissance",
  "postal_code": "Code postal",
  "tax_id": "Numéro fiscal",
  "full_name_company": "Nom complet / Raison sociale",
  "address": "Adresse",
  "save": "Enregistrer",
  "discard": "Annuler",
  "cancel": "Annuler",
  "edit": "Modifier",
  "payment": "Paiement",
  "payments": "Paiements",
  "pay_your_registration": "Payez votre inscription.",
  "registration_payment": "Paiement de l’inscription",
  "final_price": "Prix final",
  "amount": "Montant",
  "date": "Date",
  "status": "Statut",
  "pass": "Pass",
  "level": "Niveau",
  "role": "Rôle",
  "partner": "Partenaire",
  "discount_code": "Code de réduction",
  "invoice": "Facture",
  "invoices": "Factures",
  "create_invoice": "Créer une facture",
  "no_invoices": "Aucune facture disponible pour le moment.",
  "accommodation": "Hébergement",
  "choose_accommodation": "Choisissez votre hébergement",
  "no_accommodation_available": "Aucun hébergement disponible pour votre pass en ce moment.",
  "no_units_available": "Aucune unité disponible pour cet hébergement en ce moment.",
  "number_of_occupants": "Nombre d’occupants",
  "number_of_occupants_max": "Nombre d’occupants (max 12)",
  "data_of_occupants": "Données des occupants",
  "occupant": "Occupant",
  "unit": "Unité",
  "edit_accommodation": "Modifier l’hébergement",
  "cancel_reservation": "Annuler la réservation",
  "to_modify_contact_responsible": "Pour modifier cette réservation, contactez le responsable.",
  "buses": "Bus",
  "choose_bus": "Choisissez votre bus aller et/ou retour, puis enregistrez.",
  "no_spots_available": "Plus de places disponibles",
  "edit_bus": "Modifier le bus",
  "cancel_bus_reservation": "Annuler la réservation de bus",
  "confirm_cancel_bus": "Êtes-vous sûr(e) de vouloir annuler cette réservation de bus ?",
  "keep_it": "Conserver",
  "meals": "Repas",
  "tell_us_menu": "Parlez-nous de votre menu et de vos besoins alimentaires.",
  "menu": "Menu",
  "standard": "Standard",
  "vegetarian": "Végétarien",
  "allergies": "Allergies ou intolérances",
  "is_celiac": "Cœliaque / Intolérant(e) au gluten",
  "competitions": "Compétitions",
  "competition": "Compétition",
  "select_competition": "Sélectionner une compétition",
  "select_level": "Sélectionner un niveau",
  "select_role": "Sélectionner un rôle",
  "not_registered_competition": "Vous n’êtes inscrit(e) à aucune compétition.",
  "delete_competition": "Supprimer la compétition",
  "confirm_delete_competition": "Êtes-vous sûr(e) de vouloir supprimer votre inscription à",
  "actions": "Actions",
  "change_password": "Changer le mot de passe",
  "current_password": "Mot de passe actuel",
  "new_password": "Nouveau mot de passe",
  "confirm_password": "Confirmer le mot de passe",
  "your_email": "Votre email",
  "register": "S’inscrire",
  "payment_required": "Vous devez effectuer au moins un paiement partiel avant de faire cette réservation.",
  "Loading": "Chargement...",
  "choose_parties": "Choisissez vos soirées",
  "error_accept_terms": "Vous devez accepter les conditions générales pour continuer.",
  "error_required_fields": "Veuillez remplir tous les champs obligatoires.",
  "error_select_pass": "Veuillez sélectionner un pass pour continuer.",
  "group_code": "Nom du groupe / code de réduction",
  "payment_split": "Paiement en deux fois : payez 50 % maintenant et les 50 % restants dans 30 jours",
  "payment_success": "Paiement effectué !",
  "register_with_partner": "Vous inscrivez-vous avec un partenaire ?",
  "select_pass": "Choisissez votre pass",
  "select_payment": "Choisissez votre mode de paiement",
  "submit": "S’inscrire",
  "terms": "Conditions générales",
  "total_deferred": "Montant total à payer dans les 10 jours suivant la confirmation",
  "total_now": "Montant total à payer en ligne maintenant",
  "yes": "Oui",
  "role_leader": "Leader",
  "role_follower": "Suiveur/se",
  "up_accommodation": "Hébergement",
  "up_actions": "Actions",
  "up_address": "Adresse",
  "up_allergies": "Allergies ou intolérances",
  "up_amount": "Montant",
  "up_birth_date": "Date de naissance",
  "up_buses": "Bus",
  "up_cancel": "Annuler",
  "up_cancel_bus": "Annuler la réservation de bus",
  "up_cancel_reservation": "Annuler la réservation",
  "up_change_password": "Changer le mot de passe",
  "up_choose_accommodation": "Choisissez votre hébergement",
  "up_choose_bus": "Choisissez votre bus aller et/ou retour, puis enregistrez.",
  "up_city": "Ville",
  "up_competition": "Compétition",
  "up_competitions": "Compétitions",
  "up_confirm_cancel_reservation": "Êtes-vous sûr(e) de vouloir annuler cette réservation ?",
  "up_confirm_password": "Confirmer le mot de passe",
  "up_country": "Pays",
  "up_create_invoice": "Créer une facture",
  "up_current_password": "Mot de passe actuel",
  "up_data_occupants": "Données des occupants",
  "up_date": "Date",
  "up_delete_competition": "Supprimer la compétition",
  "up_departure": "Aller",
  "up_discount_code": "Code de réduction",
  "up_document": "Numéro de document",
  "up_edit_accommodation": "Modifier l’hébergement",
  "up_edit_bus": "Modifier le bus",
  "up_edit_competition_entry": "Modifier l’inscription à la compétition",
  "up_email": "Votre email",
  "up_error_password_fields": "Veuillez compléter tous les champs du mot de passe.",
  "up_error_select_competition": "Veuillez sélectionner une compétition.",
  "up_error_select_level": "Veuillez sélectionner un niveau.",
  "up_error_select_role": "Veuillez sélectionner un rôle.",
  "up_final_price": "Prix final",
  "up_first_name": "Prénom",
  "up_full_name": "Nom complet / Raison sociale",
  "up_id_expiry": "Date d’expiration CNI/Passeport",
  "up_invoice": "Facture",
  "up_invoices": "Factures",
  "up_keep_it": "Conserver",
  "up_last_name": "Nom",
  "up_level": "Niveau",
  "up_meals": "Repas",
  "up_meals_intro": "Parlez-nous de votre menu et de vos besoins alimentaires.",
  "up_menu": "Menu",
  "up_my_registration": "Mon inscription",
  "up_new_password": "Nouveau mot de passe",
  "up_no_accommodation": "Aucun hébergement disponible pour votre pass en ce moment.",
  "up_no_competition": "Vous n’êtes inscrit(e) à aucune compétition.",
  "up_no_invoices": "Aucune facture disponible pour le moment.",
  "up_no_spots": "Plus de places disponibles",
  "up_no_units": "Aucune unité disponible pour cet hébergement en ce moment.",
  "up_not_set": "Non défini",
  "up_occupant": "Occupant",
  "up_occupants": "Nombre d’occupants",
  "up_occupants_max": "Nombre d’occupants (max 12)",
  "up_partner": "Partenaire",
  "up_pass": "Pass",
  "up_pay_registration": "Payez votre inscription.",
  "up_payment": "Paiement",
  "up_payment_confirmed": "Paiement confirmé.",
  "up_payment_new_tab": "La page de paiement a été ouverte dans un nouvel onglet.",
  "up_personal_details": "Mes informations personnelles",
  "up_phone": "Téléphone",
  "up_postal_code": "Code postal",
  "up_register_competition": "S’inscrire à la compétition",
  "up_registration": "Inscription",
  "up_registration_payment": "Paiement de l’inscription",
  "up_role": "Rôle",
  "up_select_competition": "Sélectionner une compétition",
  "up_select_level": "Sélectionner un niveau",
  "up_select_role": "Sélectionner un rôle",
  "up_standard": "Standard",
  "up_standard_menu": "Menu standard",
  "up_status": "Statut",
  "up_tax_id": "Numéro fiscal",
  "up_to_modify_contact": "Pour modifier cette réservation, contactez le responsable.",
  "up_unit": "Unité",
  "up_update_profile": "Mettez à jour vos informations personnelles.",
  "up_vegetarian": "Végétarien",
  "up_vegetarian_menu": "Menu végétarien",
  "reg_all_levels_discount": "réduction appliquée pour avoir sélectionné toutes les soirées",
  "reg_code_not_found": "Code introuvable.",
  "reg_discount_applied": "Réduction de groupe appliquée",
  "reg_discount_pending": "Le groupe n’a pas encore atteint le nombre minimum de participants. La réduction sera appliquée automatiquement une fois le minimum atteint.",
  "reg_management_fee": "de frais de gestion",
  "reg_no_solo_spots": "Il n’y a pas de places individuelles disponibles pour ce rôle à ce niveau. Vous devez vous inscrire avec un partenaire ou choisir un autre niveau.",
  "reg_of_50": "du 50 %",
  "reg_of_total": "du total",
  "reg_partner_found": "Votre partenaire est déjà inscrit(e). Vous serez liés ensemble.",
  "reg_partner_not_found": "Votre partenaire n’est pas encore inscrit(e). Vous pouvez vous inscrire séparément et serez liés une fois votre partenaire inscrit.",
  "reg_payment_failed_body": "Votre inscription a été créée mais le paiement n’a pas été complété. Vous pouvez réessayer depuis le Panneau Utilisateur.",
  "reg_submitted_body": "Vérifiez votre email pour la confirmation. Vous avez 10 jours pour compléter le paiement depuis le Panneau Utilisateur.",
  "up_accommodation_reserved": "Réservation d’hébergement créée avec succès.",
  "up_accommodation_updated": "Réservation d’hébergement mise à jour avec succès.",
  "up_booked": "Réservé",
  "up_booked_in": "Vous êtes logé à",
  "up_bus_cancelled": "Réservation de bus annulée avec succès.",
  "up_bus_reserved": "Réservation de bus créée avec succès.",
  "up_bus_updated": "Réservation de bus mise à jour avec succès.",
  "up_cancelling": "Annulation...",
  "up_celiac": "Cœliaque",
  "up_competition_created": "Inscription à la compétition créée avec succès.",
  "up_competition_deleted": "Inscription à la compétition supprimée avec succès.",
  "up_competition_updated": "Inscription à la compétition mise à jour avec succès.",
  "up_confirm_cancel_accommodation": "Êtes-vous sûr(e) de vouloir annuler cette réservation d’hébergement ? Cette action est irréversible.",
  "up_confirm_delete_competition": "Êtes-vous sûr(e) de vouloir supprimer votre inscription à",
  "up_creating": "Création...",
  "up_delete": "Supprimer",
  "up_deleting": "Suppression...",
  "up_due": "Échéance",
  "up_enter_billing_details": "Entrez vos coordonnées de facturation.",
  "up_is_celiac": "Je suis Cœliaque ou intolérant(e) au gluten",
  "up_meal_saved": "Préférence de menu enregistrée avec succès.",
  "up_no_partner": "Aucun partenaire assigné",
  "up_not_booked": "Non réservé",
  "up_paid": "payé",
  "up_password_change_error": "Le mot de passe n’a pas pu être modifié.",
  "up_password_changed": "Mot de passe modifié avec succès.",
  "up_password_mismatch": "Le nouveau mot de passe et la confirmation ne correspondent pas.",
  "up_pay_now": "Payer maintenant",
  "up_pay_remaining": "Payer le reste",
  "up_payment_required": "Vous devez effectuer au moins un paiement partiel avant de faire cette réservation.",
  "up_pending": "en attente",
  "up_people": "personnes",
  "up_person": "personne",
  "up_plan_deferred": "Différé - Payer dans 10 jours",
  "up_plan_full": "Paiement complet",
  "up_plan_split": "Fractionné - 50 % maintenant, 50 % dans 30 jours",
  "up_profile_save_error": "Le profil n’a pas pu être enregistré.",
  "up_profile_saved": "Profil enregistré avec succès.",
  "up_reservation_cancelled": "Réservation annulée avec succès.",
  "up_responsible": "responsable",
  "up_save_changes": "Enregistrer les modifications",
  "up_saving": "Enregistrement...",
  "up_select_competition_details": "Sélectionnez les détails de la compétition."
}
'@

Write-Json "ca.json" @'
{
  "loading": "Carregant...",
  "registration_unavailable": "Inscripció no disponible",
  "personal_details": "Dades personals",
  "name": "Nom",
  "last_names": "Cognoms",
  "email": "Correu electrònic",
  "phone_number": "Telèfon",
  "country": "País",
  "city": "Ciutat",
  "password": "Contrasenya",
  "select_pass": "Selecciona el teu passi",
  "select_level": "Selecciona el teu nivell",
  "select_role": "Selecciona el teu rol",
  "role_leader": "Leader",
  "role_follower": "Follower",
  "individual": "Individual",
  "register_with_partner": "Et vols inscriure amb parella?",
  "yes": "Sí",
  "partner_email": "Email de la teva parella",
  "group_code": "Nom del grup / codi de descompte",
  "select_payment": "Selecciona el tipus de pagament",
  "payment_split": "Pagament dividit: paga el 50% ara i el 50% restant en 30 dies",
  "price": "Preu:",
  "total_now": "Import total a pagar en línia ara",
  "total_deferred": "Import total a pagar en els 10 dies següents a la confirmació",
  "accept_terms": "Accepto els",
  "terms": "Termes i condicions",
  "go_to_login": "Anar a l’inici de sessió",
  "submit": "Inscriure’s",
  "pay_now": "Pagar ara:",
  "payment_success": "Pagament completat!",
  "payment_failed": "El pagament ha fallat",
  "registration_confirmed": "La teva inscripció està confirmada. Revisa el teu correu electrònic.",
  "registration_submitted": "Inscripció enviada!",
  "error_required_fields": "Si us plau, completa tots els camps obligatoris.",
  "error_select_pass": "Si us plau, selecciona un passi per continuar.",
  "error_accept_terms": "Has d’acceptar els Termes i Condicions per continuar.",
  "choose_parties": "Tria les teves festes",
  "Loading": "Carregant...",
  "up_registration": "Inscripció",
  "up_payment": "Pagament",
  "up_competitions": "Competicions",
  "up_accommodation": "Allotjament",
  "up_buses": "Autobusos",
  "up_meals": "Àpats",
  "up_invoice": "Factura",
  "up_personal_details": "Les meves dades personals",
  "up_my_registration": "La meva inscripció",
  "up_update_profile": "Actualitza les teves dades personals.",
  "up_first_name": "Nom",
  "up_last_name": "Cognoms",
  "up_email": "El teu correu electrònic",
  "up_phone": "Telèfon",
  "up_city": "Ciutat",
  "up_country": "País",
  "up_document": "Número de document",
  "up_postal_code": "Codi postal",
  "up_birth_date": "Data de naixement",
  "up_cancel": "Cancel·lar",
  "up_pass": "Passi",
  "up_level": "Nivell",
  "up_role": "Rol",
  "up_partner": "Parella",
  "up_status": "Estat",
  "up_amount": "Import",
  "up_date": "Data",
  "up_pay_registration": "Paga la teva inscripció.",
  "up_registration_payment": "Pagament de la inscripció",
  "up_final_price": "Preu final",
  "up_discount_code": "Codi de descompte",
  "up_create_invoice": "Crear factura",
  "up_invoices": "Factures",
  "up_no_invoices": "Encara no hi ha factures disponibles.",
  "up_select_competition": "Selecciona una competició",
  "up_select_level": "Selecciona un nivell",
  "up_select_role": "Selecciona un rol",
  "up_no_competition": "No estàs inscrit a cap competició.",
  "up_delete_competition": "Eliminar competició",
  "up_competition": "Competició",
  "up_no_spots": "No hi ha places disponibles",
  "up_choose_accommodation": "Tria el teu allotjament",
  "up_edit_accommodation": "Editar allotjament",
  "up_cancel_reservation": "Cancel·lar reserva",
  "up_confirm_cancel_reservation": "Estàs segur/a que vols cancel·lar aquesta reserva?",
  "up_keep_it": "Mantenir",
  "up_no_accommodation": "No hi ha allotjament disponible per al teu passi en aquest moment.",
  "up_no_units": "No hi ha unitats disponibles per a aquest allotjament en aquest moment.",
  "up_occupants": "Nombre d’ocupants",
  "up_occupants_max": "Nombre d’ocupants (màx. 12)",
  "up_occupant": "Ocupant",
  "up_data_occupants": "Dades dels ocupants",
  "up_full_name": "Nom complet / Raó social",
  "up_tax_id": "NIF/CIF",
  "up_id_expiry": "Data de caducitat del document",
  "up_to_modify_contact": "Per modificar aquesta reserva, contacta amb el responsable.",
  "up_choose_bus": "Tria el teu autobús d’anada i/o tornada i desa.",
  "up_edit_bus": "Editar autobús",
  "up_cancel_bus": "Cancel·lar reserva d’autobús",
  "up_menu": "Menú",
  "up_standard": "Estàndard",
  "up_vegetarian": "Vegetarià",
  "up_allergies": "Al·lèrgies o intolerançies",
  "up_meals_intro": "Explica’ns les teves preferències de menú i necessitats dietètiques.",
  "up_unit": "Unitat",
  "up_address": "Adreça",
  "up_actions": "Accions",
  "up_change_password": "Canviar contrasenya",
  "up_current_password": "Contrasenya actual",
  "up_new_password": "Nova contrasenya",
  "up_confirm_password": "Confirmar contrasenya",
  "up_edit_competition_entry": "Editar inscripció a la competició",
  "up_error_select_competition": "Si us plau, selecciona una competició.",
  "up_error_select_level": "Si us plau, selecciona un nivell.",
  "up_payment_new_tab": "La pàgina de pagament s’ha obert en una nova pestanya.",
  "up_error_select_role": "Si us plau, selecciona un rol.",
  "up_departure": "Anada",
  "up_error_password_fields": "Si us plau, completa tots els camps de la contrasenya.",
  "up_standard_menu": "Menú estàndard",
  "up_register_competition": "Inscriure’s a la competició",
  "up_not_set": "No establert",
  "up_payment_confirmed": "Pagament confirmat.",
  "up_vegetarian_menu": "Menú vegetarià",
  "reg_all_levels_discount": "descompte aplicat per seleccionar totes les festes",
  "reg_code_not_found": "Codi no trobat.",
  "reg_discount_applied": "Descompte de grup aplicat",
  "reg_discount_pending": "El grup encara no ha assolit el nombre mínim de participants. El descompte s’aplicarà automàticament quan s’assoleixi el mínim.",
  "reg_management_fee": "de comissió de gestió",
  "reg_no_solo_spots": "No hi ha places individuals disponibles per a aquest rol en aquest nivell. Has d’inscriure’t amb parella o triar un altre nivell.",
  "reg_of_50": "del 50%",
  "reg_of_total": "del total",
  "reg_partner_found": "La teva parella ja està inscrita. Quedaréu vinculats/des.",
  "reg_partner_not_found": "La teva parella encara no està inscrita. Podeu inscriure-us per separat i quedaréu vinculats/des quan la teva parella s’inscrigui.",
  "reg_payment_failed_body": "La teva inscripció s’ha creat però el pagament no s’ha completat. Pots tornar-ho a intentar des del Panell d’Usuari.",
  "reg_submitted_body": "Revisa el teu correu per a la confirmació. Tens 10 dies per completar el pagament des del Panell d’Usuari.",
  "up_accommodation_reserved": "Reserva d’allotjament creada correctament.",
  "up_accommodation_updated": "Reserva d’allotjament actualitzada correctament.",
  "up_booked": "Reservat",
  "up_booked_in": "Esteu allotjat a",
  "up_bus_cancelled": "Reserva d’autobús cancel·lada correctament.",
  "up_bus_reserved": "Reserva d’autobús creada correctament.",
  "up_bus_updated": "Reserva d’autobús actualitzada correctament.",
  "up_cancelling": "Cancel·lant...",
  "up_celiac": "Celíac",
  "up_competition_created": "Inscripció a la competició creada correctament.",
  "up_competition_deleted": "Inscripció a la competició eliminada correctament.",
  "up_competition_updated": "Inscripció a la competició actualitzada correctament.",
  "up_confirm_cancel_accommodation": "Esteu segur/a que voleu cancel·lar aquesta reserva d’allotjament? Aquesta acció no es pot desfer.",
  "up_confirm_delete_competition": "Esteu segur/a que voleu eliminar la vostra inscripció a",
  "up_creating": "Creant...",
  "up_delete": "Eliminar",
  "up_deleting": "Eliminant...",
  "up_due": "Venciment",
  "up_enter_billing_details": "Introdueix les teves dades de facturació.",
  "up_is_celiac": "Soc Celíac/a o intolerant al gluten",
  "up_meal_saved": "Preferència de menú desada correctament.",
  "up_no_partner": "Sense parella assignada",
  "up_not_booked": "Sense reserva",
  "up_paid": "pagat",
  "up_password_change_error": "No s’ha pogut canviar la contrasenya.",
  "up_password_changed": "Contrasenya canviada correctament.",
  "up_password_mismatch": "La nova contrasenya i la confirmació no coincideixen.",
  "up_pay_now": "Pagar ara",
  "up_pay_remaining": "Pagar la resta",
  "up_payment_required": "Heu de realitzar almenys un pagament parcial abans de fer aquesta reserva.",
  "up_pending": "pendent",
  "up_people": "persones",
  "up_person": "persona",
  "up_plan_deferred": "Diferit - Pagar en 10 dies",
  "up_plan_full": "Pagament complet",
  "up_plan_split": "Fraccionat - 50% ara, 50% en 30 dies",
  "up_profile_save_error": "No s’ha pogut desar el perfil.",
  "up_profile_saved": "Perfil desat correctament.",
  "up_reservation_cancelled": "Reserva cancel·lada correctament.",
  "up_responsible": "responsable",
  "up_save_changes": "Desar canvis",
  "up_saving": "Desant...",
  "up_select_competition_details": "Selecciona els detalls de la competició."
}
'@

Write-Host "Listo. 4 JSONs actualizados con 55 keys nuevos."